name: release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.github_token }}
      - name: Build image
        run: |
          docker buildx build \
          -t ghcr.io/${{ github.repository }}:${{ github.ref_name }} \
          -t ghcr.io/${{ github.repository }}:latest \
          -f Dockerfile \
          --push \
          --platform=linux/amd64 \
          .
